version: "3.9"

services:
  nginx:
    image: igraphql/nginx:1.25.2
    container_name: nginx
    hostname: nginx
    restart: always
    networks:
      - hasura
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./source/nginx/certs:/etc/nginx/certs
      - ./source/nginx/common.conf:/etc/nginx/conf.d/common.conf
      - ./source/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./source/nginx/graphql.js:/etc/nginx/js/graphql.js
      - ./source/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./source/nginx/www:/var/www

networks:
  hasura:
    name: hasura